import '../model/family_model.dart'; // Ensure the Family model is imported
import '../model/member_model.dart';

// Create a Family instance using dummy data
final Map<String, dynamic> familyJson = {
  "its": 20377228,
  "full_name": "Shaikh Aliasgar bhai Taherali bhai Khumusi",
  "gender": "M",
  "date_of_birth": "1958-05-28",
  "age": 66,
  "first_name": "Aliasgar",
  "middle_name": "Taherali",
  "last_name": "Khumusi",
  "residence_address":
  "Flat No.B6, 2nd Floor, KDA Apartments, Block A, N.Nazimabad, Karachi, 74700",
  "residence_phone": "+923362780552",
  "image":
  "https://followup.qardanhasana.in/assets/img/mumin_photos/20377228.jpg",
  "imani_institute": "NO",
  "previous_institute": "Jinnah Government College",
  "previous_class": "Bachelors Degree Programs",
  "profile_completed": "NO",

  // Handle father as an empty list (`[]`) by assigning `null`
  "father": null,

  // Mother data
  "mother": {
    "id": 24818,
    "its_id": 40464111,
    "hof_id": 20377228,
    "mother_its": null,
    "father_its": null,
    "spouse_its": null,
    "sf_no": null,
    "jamaat_id": 1120,
    "full_name": "Batul bai Taherali bhai Surty",
    "first_name": null,
    "suffix": null,
    "father_name": null,
    "father_suffix": null,
    "father_surname": null,
    "mother_name": null,
    "surname": null,
    "dob": "1930-01-01",
    "gender": "F",
    "vatan": null,
    "martial_status": null,
    "qualification": null,
    "jamiaat": null,
    "idara": null,
    "organization": null,
    "email": "surty52@gmail.com",
    "mobile_no": "+923453387525",
    "whatsapp_no": null,
    "tanzeem": "Mahalatburhaniyah_Fakhri_Mohalla",
    "age": 85,
    "hifz_sanad": null,
    "misaq": null,
    "status": 1,
    "completed": 0,
    "hometown": null,
    "address": null,
    "current_city": null,
    "nationality": null,
    "website": null,
    "profession": null,
    "image_url":
    "https://followup.qardanhasana.in/assets/img/mumin_photos/no_user.png",
    "its_status": null,
    "marhala_ongoing": null,
    "ambition_id": 0,
    "current_marhala": 0,
    "current_class": null,
    "current_complete": 0,
    "previous_complete": 0,
    "progress": 0,
    "is_approved": 0,
    "approved_on": null,
    "approved_by": null,
    "is_delete": 1
  }
};

// Create a Family instance from JSON
Family dummyFamily = Family.fromJson(familyJson);

UserProfile userProfile11 = UserProfile(
  id: 3678,
  itsId: 20377228,
  hofId: 20377228,
  motherIts: 40464111,
  fatherIts: 0,
  spouseIts: 40464112,
  sfNo: 4533,
  jamaatId: 48,
  fullName: "Shaikh Aliasgar bhai Taherali bhai Khumusi",
  firstName: "Aliasgar",
  suffix: "bhai",
  fatherName: "Taherali",
  fatherSuffix: "bhai",
  fatherSurname: "Surti",
  motherName: null,
  surname: "Khumusi",
  dob: "1958-05-28",
  gender: "M",
  vatan: "Karachi",
  martialStatus: "Married",
  qualification: "Graduate",
  jamiaat: "Pakistan",
  idara: "Burhani Mahal Staff",
  organization: "",
  email: "surty52@gmail.com",
  mobileNo: "+923362780552",
  whatsappNo: "+923362780552",
  tanzeem: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
  age: 66,
  hifzSanad: "",
  misaq: "Done",
  status: 1,
  completed: 0,
  hometown: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
  address:
      "Flat No.B6, 2nd Floor, KDA Apartments, Block A, N.Nazimabad, Karachi,  HAHAHKEMSG:HMRDSKGMSER:GMSEKGFS 74700",
  currentCity: "Karachi",
  nationality: "Pakistani",
  website: null,
  profession: "Khidmat",
  imageUrl:
      "https://followup.qardanhasana.in/assets/img/mumin_photos/20377228.jpg",
  itsStatus: "Registered",
  marhalaOngoing: 1,
  ambitionId: 0,
  currentMarhala: 6,
  currentClass: "Bachelors Degree Programs",
  currentComplete: 1,
  previousComplete: 0,
  progress: 83,
  isApproved: 0,
  approvedOn: null,
  approvedBy: null,
  isDelete: 0,
  future: [
    FuturePlan(
      isHafiz: 0,
      isHifzNiyat: 0,
      currentHifzEnrolled: "",
      niyatHifzEnrolled: "Mahad al Zahra",
      nextSanad: 1,
      isQuranTilawat: 0,
      sehatEraab: "0",
      sehatHuroof: "0",
      isTilawatNiyat: 0,
      tilawatPreferredDays: "",
      tilawatPreferredTimings: "Morning",
      attendedCounselling: 0,
      comments: "",
      willAsbaaq: null,
      willKhidmat: null,
      study: "Pakistan",
      city: "Karachiee3e33",
      institute: "Greenwich University",
      subject: "MS Data Sciences - 2 / 2.5 yrs",
      country: "Pakistan",
      isRelative: 0,
      relation: "",
      relativeIts: 0,
    )
  ],
  education: [
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 6,
      standard: "Education",
      standardId: 124,
      className: "Bachelors Degree Programs",
      startDate: "1978-01-01",
      endDate: "1980-01-01",
      country: "Pakistan",
      city: "Karachi00",
      imaniOtherSchool: 0,
      institute: "Jinnah Government College",
      subject: "BSc/Statistic",
      duration: 24,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 5,
      standard: "HSSC-(Provincial Board)",
      standardId: 135,
      className: "12th",
      startDate: "1976-01-01",
      endDate: "1977-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Federal Govt. College Hyd",
      subject: "Pre-Engineering",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 5,
      standard: "HSSC-(Provincial Board)",
      standardId: 135,
      className: "11th",
      startDate: "1975-01-01",
      endDate: "1976-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "None",
      subject: "Pre-Engineering",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 4,
      standard: "SSC-(Provincial Board)",
      standardId: 130,
      className: "10th",
      startDate: "1974-01-01",
      endDate: "1975-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: "Pre Engineering",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 4,
      standard: "SSC-(Provincial Board)",
      standardId: 130,
      className: "9th",
      startDate: "1973-01-01",
      endDate: "1974-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: "Pre Engineering",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 3,
      standard: "STD 8",
      standardId: 13,
      className: "8th",
      startDate: "1972-01-01",
      endDate: "1973-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 3,
      standard: "STD 7",
      standardId: 12,
      className: "7th",
      startDate: "1971-01-01",
      endDate: "1972-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 3,
      standard: "STD 6",
      standardId: 11,
      className: "6th",
      startDate: "1970-01-01",
      endDate: "1971-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 3,
      standard: "STD 5",
      standardId: 10,
      className: "5th",
      startDate: "1969-01-01",
      endDate: "1970-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 2,
      standard: "STD 4",
      standardId: 9,
      className: "4th",
      startDate: "1968-01-01",
      endDate: "1969-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 2,
      standard: "STD 3",
      standardId: 8,
      className: "3rd",
      startDate: "1967-01-01",
      endDate: "1968-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "Public School Hyderabad",
      subject: null,
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: null,
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 2,
      standard: "STD 2",
      standardId: 7,
      className: "2nd",
      startDate: "1966-01-01",
      endDate: "1967-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "St. Bonaventure's Higher Secondary School",
      subject: "",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 2,
      standard: "STD 1",
      standardId: 6,
      className: "1st",
      startDate: "1965-01-01",
      endDate: "1966-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "St. Bonaventure's Higher Secondary School",
      subject: "",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
    Education(
      jamaat: "KHI (AL-MAHALAT-TUL-BURHANIYAH)",
      marhalaId: 1,
      standard: "Nursery",
      standardId: 2,
      className: "Nursery",
      startDate: "1962-01-01",
      endDate: "1963-01-01",
      country: "Pakistan",
      city: "Hyderabad Sindh",
      imaniOtherSchool: 0,
      institute: "St. Bonaventure's Higher Secondary School",
      subject: "",
      duration: 12,
      scholarshipTaken: 0,
      scholarship: "",
      qardan: "None",
      status: "V",
    ),
  ],
);
